export enum BonusType {
  WELCOME_MATCH = "WELCOME_MATCH",
  RELOAD_MATCH = "RELOAD_MATCH",
  FREEBET = "FREEBET",
  FREE_SPINS = "FREE_SPINS",
  CASHBACK_LOSS = "CASHBACK_LOSS",
  CASHBACK_DEPOSIT = "CASHBACK_DEPOSIT",
  RISK_FREE_BET = "RISK_FREE_BET",
  REFERRAL = "REFERRAL",
  LOYALTY = "LOYALTY",
  COMP_POINTS = "COMP_POINTS",
  NO_DEPOSIT = "NO_DEPOSIT",
  PERSONALIZED = "PERSONALIZED",
}

export enum BonusStatus {
  AVAILABLE = "AVAILABLE",
  ACTIVE = "ACTIVE",
  LOCKED = "LOCKED",
  ROLLOVER_COMPLETE = "ROLLOVER_COMPLETE",
  RELEASED = "RELEASED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
  USED = "USED",
  VOID = "VOID",
}

export enum BonusTrigger {
  MANUAL = "MANUAL",
  FIRST_DEPOSIT = "FIRST_DEPOSIT",
  DEPOSIT = "DEPOSIT",
  SIGNUP = "SIGNUP",
  BET_WON = "BET_WON",
  BET_LOST = "BET_LOST",
  LOYALTY_LEVEL = "LOYALTY_LEVEL",
  REFERRAL_SIGNUP = "REFERRAL_SIGNUP",
  REFERRAL_DEPOSIT = "REFERRAL_DEPOSIT",
  WEEKLY_SCHEDULED = "WEEKLY_SCHEDULED",
  MONTHLY_SCHEDULED = "MONTHLY_SCHEDULED",
  CAMPAIGN_CODE = "CAMPAIGN_CODE",
  BIRTHDAY = "BIRTHDAY",
}

export enum CampaignStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  EXPIRED = "EXPIRED",
  ARCHIVED = "ARCHIVED",
}

export enum CasinoContributionCategory {
  SLOTS_ONLY = "SLOTS_ONLY",
  STANDARD_MIX = "STANDARD_MIX",
  TABLES_ONLY = "TABLES_ONLY",
  LIVE_DEALER_EXCLUDED = "LIVE_DEALER_EXCLUDED",
  SPORTS_ONLY = "SPORTS_ONLY",
}

export enum RolloverStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETE = "COMPLETE",
  EXPIRED = "EXPIRED",
  FORFEITED = "FORFEITED",
  RELEASED = "RELEASED",
}
