export enum CasinoGameCategory {
  SLOTS = "SLOTS",
  ROULETTE = "ROULETTE",
  BLACKJACK = "BLACKJACK",
  BACCARAT = "BACCARAT",
  POKER = "POKER",
  CRAPS = "CRAPS",
  KENO = "KENO",
  SCRATCH_CARDS = "SCRATCH_CARDS",
  BINGO = "BINGO",
  LIVE_DEALER = "LIVE_DEALER",
  LIVE_ROULETTE = "LIVE_ROULETTE",
  LIVE_BLACKJACK = "LIVE_BLACKJACK",
  LIVE_BACCARAT = "LIVE_BACCARAT",
  GAME_SHOW = "GAME_SHOW",
  VIRTUAL_SPORTS = "VIRTUAL_SPORTS",
  JACKPOT = "JACKPOT",
  MEGA_WAYS = "MEGA_WAYS",
}

export enum CasinoGameStatus {
  ACTIVE = "ACTIVE",
  MAINTENANCE = "MAINTENANCE",
  DISABLED = "DISABLED",
  COMING_SOON = "COMING_SOON",
}

export enum CasinoBetStatus {
  PLACED = "PLACED",
  WON = "WON",
  LOST = "LOST",
  PUSH = "PUSH",
  VOID = "VOID",
  FREE_SPIN = "FREE_SPIN",
  BONUS_GAME = "BONUS_GAME",
}

export enum CasinoProvider {
  MOCK = "MOCK",
  BIGBANG = "BIGBANG",
  PGSOFT = "PGSOFT",
  EVOLUTION = "EVOLUTION",
  PRAGMATIC = "PRAGMATIC",
  NETENT = "NETENT",
  MICROGAMING = "MICROGAMING",
  PLAYTECH = "PLAYTECH",
  YGGDRASIL = "YGGDRASIL",
  QUICKSPIN = "QUICKSPIN",
  RED_TIGER = "RED_TIGER",
  PLAY_N_GO = "PLAY_N_GO",
  HABANERO = "HABANERO",
  BOOMING = "BOOMING",
}

export { CasinoProvider as CasinoGameProvider };

export enum CasinoSessionStatus {
  INITIATED = "INITIATED",
  ACTIVE = "ACTIVE",
  CLOSED = "CLOSED",
  TIMED_OUT = "TIMED_OUT",
  ERROR = "ERROR",
  KYC_REQUIRED = "KYC_REQUIRED",
  SELF_EXCLUDED = "SELF_EXCLUDED",
}
