export enum KYCLevel {
  L0 = 0,
  L1 = 1,
  L2 = 2,
  L3 = 3,
}

export enum KYCStatus {
  NOT_STARTED = "NOT_STARTED",
  INITIATED = "INITIATED",
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
  RETRY = "RETRY",
}

export enum KYCRejectionReason {
  INVALID_DOCUMENT = "INVALID_DOCUMENT",
  EXPIRED_DOCUMENT = "EXPIRED_DOCUMENT",
  POOR_IMAGE_QUALITY = "POOR_IMAGE_QUALITY",
  SELFIE_MISMATCH = "SELFIE_MISMATCH",
  MISMATCH_NAME = "MISMATCH_NAME",
  MISMATCH_ADDRESS = "MISMATCH_ADDRESS",
  AGE_RESTRICTION = "AGE_RESTRICTION",
  JURISDICTION_RESTRICTION = "JURISDICTION_RESTRICTION",
  OTHER = "OTHER",
}
