export enum NotificationChannel {
  IN_APP = "IN_APP",
  EMAIL = "EMAIL",
  SMS = "SMS",
  PUSH_WEB = "PUSH_WEB",
  PUSH_FCM = "PUSH_FCM",
  PUSH_APNS = "PUSH_APNS",
  WHATSAPP = "WHATSAPP",
  TELEGRAM = "TELEGRAM",
}

export enum NotificationCategory {
  GENERAL = "GENERAL",
  BET_PLACED = "BET_PLACED",
  BET_WON = "BET_WON",
  BET_LOST = "BET_LOST",
  BET_SETTLED = "BET_SETTLED",
  CASHOUT_COMPLETED = "CASHOUT_COMPLETED",
  DEPOSIT_PENDING = "DEPOSIT_PENDING",
  DEPOSIT_COMPLETED = "DEPOSIT_COMPLETED",
  DEPOSIT_FAILED = "DEPOSIT_FAILED",
  WITHDRAWAL_REQUESTED = "WITHDRAWAL_REQUESTED",
  WITHDRAWAL_COMPLETED = "WITHDRAWAL_COMPLETED",
  WITHDRAWAL_REJECTED = "WITHDRAWAL_REJECTED",
  KYC_STATUS_CHANGED = "KYC_STATUS_CHANGED",
  KYC_REVIEW_REQUESTED = "KYC_REVIEW_REQUESTED",
  BONUS_GRANTED = "BONUS_GRANTED",
  BONUS_EXPIRING = "BONUS_EXPIRING",
  BONUS_ROLLOVER_COMPLETE = "BONUS_ROLLOVER_COMPLETE",
  PROMOTIONAL = "PROMOTIONAL",
  CASINO_BIG_WIN = "CASINO_BIG_WIN",
  LIVE_EVENT_STARTED = "LIVE_EVENT_STARTED",
  FAVORITE_TEAM_SCORED = "FAVORITE_TEAM_SCORED",
  SECURITY_LOGIN = "SECURITY_LOGIN",
  SECURITY_PASSWORD_CHANGED = "SECURITY_PASSWORD_CHANGED",
  SECURITY_2FA_CHANGED = "SECURITY_2FA_CHANGED",
  SUPPORT_REPLY = "SUPPORT_REPLY",
  RESPONSIBLE_GAMING_ALERT = "RESPONSIBLE_GAMING_ALERT",
  SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE",
}

export enum NotificationPreferenceScope {
  GLOBAL = "GLOBAL",
  CATEGORY = "CATEGORY",
  CHANNEL = "CHANNEL",
  EVENT = "EVENT",
}

export enum NotificationStatus {
  PENDING = "PENDING",
  QUEUED = "QUEUED",
  SENDING = "SENDING",
  SENT = "SENT",
  DELIVERED = "DELIVERED",
  READ = "READ",
  FAILED = "FAILED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
  SUPPRESSED = "SUPPRESSED",
  OPTED_OUT = "OPTED_OUT",
}

export enum DevicePlatform {
  WEB_PUSH = "WEB_PUSH",
  FCM_ANDROID = "FCM_ANDROID",
  FCM_IOS = "FCM_IOS",
  APNS_IOS = "APNS_IOS",
  APNS_MACOS = "APNS_MACOS",
}
