export enum LedgerAccountType {
  USER_REAL_BALANCE = "USER_REAL_BALANCE",
  USER_BONUS_BALANCE = "USER_BONUS_BALANCE",
  HOUSE_BALANCE = "HOUSE_BALANCE",
  HOUSE_RESERVE = "HOUSE_RESERVE",
  PENDING_DEPOSITS = "PENDING_DEPOSITS",
  PENDING_WITHDRAWALS = "PENDING_WITHDRAWALS",
  PENDING_BETS = "PENDING_BETS",
  BONUS_EXPENSE = "BONUS_EXPENSE",
  CASINO_WINS_EXPENSE = "CASINO_WINS_EXPENSE",
  FEES_INCOME = "FEES_INCOME",
  CASHOUT_PAYMENTS = "CASHOUT_PAYMENTS",
}

export enum LedgerEntryType {
  DEBIT = "DEBIT",
  CREDIT = "CREDIT",
}

export enum TransactionType {
  DEPOSIT = "DEPOSIT",
  WITHDRAWAL = "WITHDRAWAL",
  BET_PLACED = "BET_PLACED",
  BET_SETTLED_WON = "BET_SETTLED_WON",
  BET_SETTLED_LOST = "BET_SETTLED_LOST",
  BET_SETTLED_HALF_WON = "BET_SETTLED_HALF_WON",
  BET_SETTLED_HALF_LOST = "BET_SETTLED_HALF_LOST",
  BET_SETTLED_VOID = "BET_SETTLED_VOID",
  BET_CASHOUT = "BET_CASHOUT",
  BONUS_GRANTED = "BONUS_GRANTED",
  BONUS_RELEASED = "BONUS_RELEASED",
  BONUS_EXPIRED = "BONUS_EXPIRED",
  FREEBET_GRANTED = "FREEBET_GRANTED",
  CASHOUT_FEE = "CASHOUT_FEE",
  WITHDRAWAL_FEE = "WITHDRAWAL_FEE",
  CASINO_BET = "CASINO_BET",
  CASINO_WIN = "CASINO_WIN",
  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  AFFILIATE_PAYMENT = "AFFILIATE_PAYMENT",
}

export enum PaymentProvider {
  STRIPE = "STRIPE",
  SKRILL = "SKRILL",
  NETELLER = "NETELLER",
  BANK_TRANSFER = "BANK_TRANSFER",
  PAYPAL = "PAYPAL",
  PAYSAFE_CARD = "PAYSAFE_CARD",
  APPLE_PAY = "APPLE_PAY",
  GOOGLE_PAY = "GOOGLE_PAY",
  MB_WAY = "MB_WAY",
  MULTIBANCO = "MULTIBANCO",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
  REQUIRES_ACTION = "REQUIRES_ACTION",
  UNDER_REVIEW = "UNDER_REVIEW",
}
