export const BET62_EVENTS = {
  AUTH: {
    USER_CREATED: "auth.user.created",
    USER_LOGGED_IN: "auth.user.logged_in",
    USER_LOGGED_OUT: "auth.user.logged_out",
    USER_EMAIL_VERIFIED: "auth.user.email_verified",
    USER_PASSWORD_CHANGED: "auth.user.password_changed",
    USER_PASSWORD_RESET: "auth.user.password_reset",
    USER_2FA_ENABLED: "auth.user.2fa_enabled",
    USER_2FA_DISABLED: "auth.user.2fa_disabled",
    USER_ACCOUNT_SUSPENDED: "auth.user.account_suspended",
    USER_ACCOUNT_LOCKED: "auth.user.account_locked",
  },
  USER: {
    PROFILE_UPDATED: "user.profile.updated",
    PREFERENCES_UPDATED: "user.preferences.updated",
    LIMITS_CHANGED: "user.limits.changed",
    SELF_EXCLUDED: "user.self_excluded",
    SELF_EXCLUSION_ENDED: "user.self_exclusion_ended",
    REALITY_CHECK_ACK: "user.reality_check.acknowledged",
  },
  KYC: {
    LEVEL_UPDATED: "kyc.level.updated",
    VERIFICATION_SUBMITTED: "kyc.verification.submitted",
    VERIFICATION_APPROVED: "kyc.verification.approved",
    VERIFICATION_REJECTED: "kyc.verification.rejected",
    VERIFICATION_EXPIRED: "kyc.verification.expired",
  },
  WALLET: {
    DEPOSIT_CREATED: "wallet.deposit.created",
    DEPOSIT_COMPLETED: "wallet.deposit.completed",
    DEPOSIT_FAILED: "wallet.deposit.failed",
    WITHDRAWAL_REQUESTED: "wallet.withdrawal.requested",
    WITHDRAWAL_APPROVED: "wallet.withdrawal.approved",
    WITHDRAWAL_REJECTED: "wallet.withdrawal.rejected",
    WITHDRAWAL_COMPLETED: "wallet.withdrawal.completed",
    WITHDRAWAL_FAILED: "wallet.withdrawal.failed",
    BALANCE_UPDATED: "wallet.balance.updated",
    WALLET_FROZEN: "wallet.frozen",
    WALLET_UNFROZEN: "wallet.unfrozen",
    INTERNAL_DEBIT: "wallet.internal.debit",
    INTERNAL_CREDIT: "wallet.internal.credit",
  },
  ODDS: {
    PREMATCH_SYNCED: "odds.prematch.synced",
    LIVE_SYNCED: "odds.live.synced",
    ODD_CHANGED: "odds.odd.changed",
    EVENT_STARTED: "odds.event.started",
    EVENT_LIVE_UPDATED: "odds.event.live_updated",
    EVENT_SCORE_UPDATED: "odds.event.score_updated",
    EVENT_ENDED: "odds.event.ended",
    EVENT_SUSPENDED: "odds.event.suspended",
    EVENT_CANCELLED: "odds.event.cancelled",
    MARKET_SUSPENDED: "odds.market.suspended",
    MARKET_UNSUSPENDED: "odds.market.unsuspended",
    LIVE_GOAL_SCORED: "odds.live.goal_scored",
    LIVE_CARD_SHOWN: "odds.live.card_shown",
    LIVE_EVENT_HAPPENED: "odds.live.event_happened",
  },
  BETS: {
    PLACED: "bets.bet.placed",
    REJECTED: "bets.bet.rejected",
    CANCELLED: "bets.bet.cancelled",
    WON: "bets.bet.won",
    LOST: "bets.bet.lost",
    HALF_WON: "bets.bet.half_won",
    HALF_LOST: "bets.bet.half_lost",
    VOID: "bets.bet.void",
    SETTLED: "bets.bet.settled",
    CASHOUT_REQUESTED: "bets.cashout.requested",
    CASHOUT_CONFIRMED: "bets.cashout.confirmed",
    CASHOUT_REJECTED: "bets.cashout.rejected",
    AUTO_CASHOUT_TRIGGERED: "bets.auto_cashout.triggered",
    RISK_FLAGGED: "bets.risk.flagged",
  },
  BONUS: {
    CAMPAIGN_ACTIVATED: "bonus.campaign.activated",
    CAMPAIGN_EXPIRED: "bonus.campaign.expired",
    GRANTED: "bonus.user.granted",
    ACTIVATED: "bonus.user.activated",
    EXPIRED: "bonus.user.expired",
    ROLLOVER_COMPLETE: "bonus.user.rollover_complete",
    RELEASED: "bonus.user.released",
    CANCELLED: "bonus.user.cancelled",
    USED_IN_BET: "bonus.user.used_in_bet",
  },
  CASINO: {
    SESSION_STARTED: "casino.session.started",
    SESSION_ENDED: "casino.session.ended",
    BET_PLACED: "casino.bet.placed",
    BET_WON: "casino.bet.won",
    BET_LOST: "casino.bet.lost",
    JACKPOT_WON: "casino.jackpot.won",
    FREE_SPINS_AWARDED: "casino.free_spins.awarded",
    BONUS_GAME_TRIGGERED: "casino.bonus_game.triggered",
  },
  NOTIFICATIONS: {
    QUEUE_EMAIL: "notifications.queue.email",
    QUEUE_PUSH: "notifications.queue.push",
    QUEUE_SMS: "notifications.queue.sms",
    QUEUE_INAPP: "notifications.queue.inapp",
    SENT: "notifications.sent",
    FAILED: "notifications.failed",
    READ: "notifications.read",
  },
  ADMIN: {
    ADMIN_LOGIN: "admin.login",
    ADMIN_ACTION: "admin.action",
    USER_BANNED: "admin.user.banned",
    USER_UNBANNED: "admin.user.unbanned",
    USER_LIMITS_OVERRIDDEN: "admin.user.limits_overridden",
    BET_LIQUIDATED_MANUAL: "admin.bet.liquidated_manual",
    BET_VOIDED_MANUAL: "admin.bet.voided_manual",
    ODD_OVERRIDDEN: "admin.odd.overridden",
    MARKET_SUSPENDED_MANUAL: "admin.market.suspended_manual",
    WALLET_ADJUSTMENT: "admin.wallet.adjustment",
    WITHDRAWAL_APPROVED: "admin.withdrawal.approved",
    WITHDRAWAL_REJECTED: "admin.withdrawal.rejected",
    BONUS_MANUAL_GRANT: "admin.bonus.manual_grant",
  },
} as const;

export type Bet62EventChannel =
  | (typeof BET62_EVENTS.AUTH)[keyof typeof BET62_EVENTS.AUTH]
  | (typeof BET62_EVENTS.USER)[keyof typeof BET62_EVENTS.USER]
  | (typeof BET62_EVENTS.KYC)[keyof typeof BET62_EVENTS.KYC]
  | (typeof BET62_EVENTS.WALLET)[keyof typeof BET62_EVENTS.WALLET]
  | (typeof BET62_EVENTS.ODDS)[keyof typeof BET62_EVENTS.ODDS]
  | (typeof BET62_EVENTS.BETS)[keyof typeof BET62_EVENTS.BETS]
  | (typeof BET62_EVENTS.BONUS)[keyof typeof BET62_EVENTS.BONUS]
  | (typeof BET62_EVENTS.CASINO)[keyof typeof BET62_EVENTS.CASINO]
  | (typeof BET62_EVENTS.NOTIFICATIONS)[keyof typeof BET62_EVENTS.NOTIFICATIONS]
  | (typeof BET62_EVENTS.ADMIN)[keyof typeof BET62_EVENTS.ADMIN];

export const BET62_STREAMS = {
  MAIN: "bet62:stream:main",
  AUTH: "bet62:stream:auth",
  USER: "bet62:stream:user",
  KYC: "bet62:stream:kyc",
  WALLET: "bet62:stream:wallet",
  ODDS: "bet62:stream:odds",
  BETS: "bet62:stream:bets",
  BONUS: "bet62:stream:bonus",
  CASINO: "bet62:stream:casino",
  NOTIFICATIONS: "bet62:stream:notifications",
  ADMIN: "bet62:stream:admin",
  FINANCE: "bet62:stream:finance",
} as const;

export const BET62_QUEUES = {
  EMAIL: "bet62:queue:email",
  PUSH: "bet62:queue:push",
  SMS: "bet62:queue:sms",
  ODDS_SYNC_PREMATCH: "bet62:queue:odds:sync-prematch",
  ODDS_SYNC_LIVE: "bet62:queue:odds:sync-live",
  BETS_SETTLE: "bet62:queue:bets:settle",
  KYC_WEBHOOK: "bet62:queue:kyc:webhook",
  STRIPE_WEBHOOK: "bet62:queue:stripe:webhook",
  AUDIT_LOG: "bet62:queue:audit:log",
  REPORT_GENERATE: "bet62:queue:reports:generate",
} as const;
